### ISSUE TITLE
Corrupt JSON file prevents retrieval/display of weather

### ISSUE THREAD

**Issue by jeffbyrnes** [jason0x43/jc-weather#8]
Filing this just in case anyone else comes by.

Debug log output in Alfred:

```
Starting debug for 'Weather'

[STDERR: alfred.workflow.input.scriptfilter] [2015-05-31 07:05:28,320] DEBUG: jcalfred.alfred: tell(weather, )
[2015-05-31 07:05:28,321] DEBUG: alfred_weather: getting weather from Forecast.io
[2015-05-31 07:05:28,325] WARNING: jcalfred.jsonfile: corrupt JsonFile /Users/jeffbyrnes/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data/jc-weather/data.json
[2015-05-31 07:05:28,325] ERROR: jcalfred.alfred: Error telling
Traceback (most recent call last):
  File "jcalfred/alfred.py", line 491, in tell
    items = getattr(self, cmd)(query)
  File "alfred_weather.py", line 775, in tell_weather
    weather = self._get_weather(location)
  File "alfred_weather.py", line 317, in _get_weather
    weather = self._get_fio_weather()
  File "alfred_weather.py", line 433, in _get_fio_weather
    data = self._load_cached_data('fio', location)
  File "alfred_weather.py", line 254, in _load_cached_data
    if service not in self.cache:
  File "alfred_weather.py", line 129, in cache
    self._cache = JsonFile(self.cache_file)
  File "jcalfred/jsonfile.py", line 38, in __init__
    self._data = json.loads(''.join(lines))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 368, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1477 column 2 - line 1479 column 2 (char 51062 - 51069)
[INFO: alfred.workflow.input.scriptfilter] <?xml version="1.0"?><items><item valid="no"><title>Error: Extra data: line 1477 column 2 - line 1479 column 2 (char 51062 - 51069)</title><icon>icon.png</icon></item></items>
```

**Comment by jeffbyrnes** [comment]
Deleting the JSON file allows the workflow to work again.
